#+STARTUP: hidestars

* Start with 2-3 plants and understand balconies climate/requirements of plants
* South facing balcony needs to be watered more often
** Opt watering at ground level. Avoid watering the foliage as it encourages the development of diseases.
** Use self watering containers
** Incorporate [[https://www.amazon.com/Dirty-Gardener-Water-Retention-Granules/dp/B004SD3R2I][Water Retention Granules]] in soil of your potted plants. They absorb water and release it slowly. This slows down the frequency of watering.
** Adopt mulching.
It helps in retaining moisture. It is a quick and easy task in small garden on balcony or terrace. Place the mulch on a surface of soil.
You can use bark, leaves and wood chips. If you want to add decorative
element, use gravel and pebbles to much.
** Do not water unnecessarily. Check the moisture content of soil under the surface layer. Poke your finger two inches deep and see if the soil is moist or dry, when only when you find it dry or semi dry.
If you have a roofless balcony or terrace, water scarcely in rainy season.
** Water preferably in the morning before the first rays of the sun, this is the best watering time.
* After transplanting or to young plants, water frequently but in small amounts because young plants are more susceptible to dry shots.
When the plants mature and establish, increase their watering interval, for instance, water every other day if you were watering everyday.
Also increase the amount of water, water full and deeply. This prevents the roots remain shallow.
* Lot of exposure: choose to grow shrubs– citrus, oleander, gardenia, shrub roses or heather in a pot.
* Vegetabels
  A few edibles like tomatoes, peppers, chilies, eggplants, many green leafy vegetables plus all the herbs grow well. For complete information, read our guide on balcony vegetable garden.
* [[https://balconygardenweb.com/make-a-balcony-herb-garden/][Balcony Herb Garden]]
* Avoid using too many small planters (looks too busy)
* Terracotta pots for the balcony garden because it’s a windy and hotter space and terracotta pots keep the soil cool and drain excess water.
* Installing birdbath and bird feeder is also a good idea.
* Mulching. It helps in containing moisture in soil.
